BorletteDemoMVCCore/Models/ErrorViewModel.cs
namespace BorletteDemoMVCCore.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BorletteDemoMVCCore/Controllers/HomeController.cs
using BorletteDemoMVCCore.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BorletteDemoMVCCore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BorletteDemoMVCCore/Controllers/TirageController.cs
using BorletteDTO;
using BorletteRepository.Factory;
using Microsoft.AspNetCore.Mvc;

namespace BorletteDemoMVCCore.Controllers
{
    public class TirageController : Controller
    {
        private IDAOFactory _factory;
        public TirageController(IDAOFactory fact) { 
            _factory = fact;
        }

        public IActionResult Index()
        {
           List<Tirage> tirages= _factory.CreateInstanceDAOTirage().GetAllTirage();
           return View(tirages);
        }
    }
}

BorletteDemoMVCCore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BorletteDemoMVCCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BorletteDemoMVCCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BorletteDemoMVCCore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BorletteDemoMVCCore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tirage" asp-action="Index">Tirage Loto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BorletteDemoMVCCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BorletteDemoMVCCore/Views/Tirage/Index.cshtml
@using BorletteDTO
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model List<Tirage>
@{
    ViewData["Title"] = "TIRAGE";
}

<h2>LOTO SA : TIRAGE</h2>
<table class="table table-condensed table-striped">
    <tr>
        <th>Date Tirage</th>
        <th>Majoration Gain(1er Lot)</th>
        <th>1er Lot</th>
        <th>Majoration Gain(2eme Lot)</th>
        <th>2eme Lot</th>
        <th>Majoration Gain(3eme Lot)</th>
        <th>3eme Lot</th>
        <th>Statut</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.CreeLe</td>
            <td>@item.CoefficientPremierNumero</td>
            <td>@item.PremierNumero</td>
            <td>@item.CoefficientDeuxiemeNumero</td>
            <td>@item.DeuxiemeNumero</td>
            <td>@item.CoefficientTroisiemeNumero</td>
            <td>@item.TroisiemeNumero</td>
            <td>@item.LibelleStatut</td>
        </tr>
    }
</table>